name: Integracion Continua
on:
  push:
    branches-ignore:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instalar dependencias
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Instalar Playwright
        run: npx playwright install
      - name: Correr Playwright
        run: npm run playwright
        env:
          CI: true