name: Integracion Continua
on:
  push:
    branches-ignore:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Instalar dependencias
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Instalar Playwright
        run: npx playwright install
      - name: Levantar wiremock
        run: java -jar .wiremock/wiremock-standalone-3.3.1.jar
      - name: Correr Playwright
        run: npm run playwright
        env:
          CI: true
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1