name: Integracion Continua
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build app
        run: npm run build
      - name: Correr Tests End To End
        run: npm run playwright
        env:
          CI: true