name: Integracion Continua
on:
  push:
    branches-ignore:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Levantar wiremock
        run: |
          docker run -d --name wiremock -p 8080:8080 \
            --health-cmd "curl --fail http://localhost:8080/__admin/health" \
            --health-interval 10s --health-timeout 5s --health-retries 5 \
            -v ${{ github.workspace }}/data/.wiremock/mappings:/home/wiremock/mappings \
            -v ${{ github.workspace }}/data/.wiremock/__files:/home/wiremock/__files \
            wiremock/wiremock:2.31.0
      - name: Obtnener IP de Wiremock
        id: wiremock_ip
        run: |
          {
            WIREMOCK_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' wiremock)
            echo "WIREMOCK_IP=$WIREMOCK_IP"
          } >> "$GITHUB_OUTPUT"
      - name: Instalar dependencias
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Instalar Playwright
        run: npx playwright install
      - name: Correr Playwright
        run: npm run playwright
        env:
          CI: true
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
      - uses: dedene/curl@v1
        if: failure()
        env:
          HOST: ${{ steps.wiremock_ip.outputs.WIREMOCK_IP }}
        with:
          url: http://$HOST:8080/__admin/requests
          args: -v